# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d6b2fcdeca0133d919eb17848376aea535af116f674c0c05722347b82f4443770f5416855d97c2770c154f080b310c08017ec4ef3c36b0d919bfbe0a685a6812

test:
  secret_key_base: 5055a91f2b111a7bc0c1cdcd4faccc64eb18edf8612ef87e361ca92db211bd18612095072bf237bedf1f6c42824a5235c57de79e45b391ca28ea4438017a8d07

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
